# -*- coding: utf-8 -*-
"""Rainie Fanita C.H (71230982) 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jvzAlCH4DN0PvNW9dOXnLg-jsUFq1Cpq

**LATIHAN 7.1**

Buatlah sebuah program yang dapat mendeteksi apakah suatu kata adalah anagram
dari kata lainnya atau bukan! Anagram adalah kata yang dibolak-balik susunan hurufnya sama.
> Misal: mata anagram dengan atma, maat, taam, tama, dsb.
"""

def anagram(kata1, kata2):
  if sorted(kata1.lower()) and sorted(kata2.lower()):
    print(f"{kata1} dan {kata2} adalah anagram")
  else:
    print(f"{kata1} dan {kata2} bukan anagram")

kata1 = input("Masukkan kata 1 = ")
kata2 = input("Masukkan kata 2 = ")

anagram(kata1, kata2)

"""**LATIHAN 7.2**

Buatlah suatu program yang dapat menghitung frekuensi kemunculan suatu kata
yang ada pada String.
> Misal terdapat kalimat "Saya mau makan. Makan itu wajib. Mau siang atau malam saya wajib makan". <BR>
> Ditanyakan kata "makan". Output: makan ada 3 buah
"""

def hitung(kalimat, kata) :
    kalimat = kalimat.lower()
    kata = kata.lower()
    hasil = kalimat.count(kata)
    return hasil

kalimat = input("masukkan kalimat : ")
kata = input("masukkan kata : ")

print(hitung(kalimat,kata))

"""**LATIHAN 7.3**

Buatlah suatu program yang dapat menghapus semua spasi yang berlebih pada
sebuah string, dan menjadikannya satu spasi normal!
> Misal: "saya tidak suka memancing ikan " <BR>
> Output: "saya tidak suka memancing ikan"
"""

def spasi(kalimat):
  bener = " ".join(kalimat.split())
  bener = bener.strip()
  print(bener)

kalimat= input("Masukkan kalimat = ")

spasi(kalimat)

"""**LATIHAN 7.4**

Buatlah suatu program mengetahui kata terpendek dan terpanjang dari suatu
kalimat yang diinputkan!
> Misal: "red snakes and a black frog in the pool" <BR>
> Output: terpendek: a, terpanjang: snakes
"""

def hitung(kalimat):
  pisah = kalimat.split()

  terpendek = min(pisah, key=len)
  terpanjang = max(pisah, key=len)

  print("terpendek = ", terpendek)
  print("terpanjang = ", terpanjang)

kalimat = input("Masukkan kalimat = ")

hitung(kalimat)
