# -*- coding: utf-8 -*-
"""Rainie Fanita C.H.(71230982) 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MUpsglDSOEjzXQuWm5oMOFnBNPvTxcGE

**LATIHAN 5.1**

Buatlah program yang menerapkan perhitungan perkalian dengan menggunakan penjumlahan. Buatlah fungsi perkalian() dalam program tersebut! Berikut ini adalah beberapa contoh perhitungan yang diharapkan:
*   6 x 5 = 5 + 5 + 5 + 5 + 5 + 5 = 30.
*   7 x 10 = 10 + 10 + 10 + 10 + 10 + 10 + 10 = 70.
"""

def perkalian( kali, bilangan ):
  print(f"{kali} x {bilangan} =", end=" ")
  hasil = 0
  for i in range(kali):
    if i < kali-1:
      print(bilangan, end=" + ")
    elif i == kali-1:
      print(bilangan, end=" ")

    hasil += bilangan

  print(f"= {hasil}")

kali = int(input("Masukkan pengali= "))
bilangan = int(input("Masukkan bilangan= "))

perkalian(kali, bilangan)

"""**LATIHAN 5.2**

Buatlah program yang dapat menampilkan deret bilangan ganjil dari batas bawah dan batas atas yang diberikan oleh pengguna. Jika ternyata batas atas < batas bawah, berarti deret tersebut dimulai dari batas atas, sampai batas bawah (negatif range). Buatlah fungsi ganjil() dalam program tersebut! Berikut ini adalah contoh hasil yang diharapkan:
* bawah = 10, atas = 30. Karena bawah < atas, berarti dari kecil ke besar, maka hasilnya adalah: 11, 13, 15, 17, 19, 21, 23, 25, 27, 29.
* bawah = 97, atas = 82. Karena bawah > atas, berarti dari besar ke kecil, maka hasilnya adalah: 97, 95, 93, 91, 89, 87, 85, 83.
"""

def ganjil(bawah, atas):
  if bawah <= atas:
    for i in range(bawah, atas):
      if i % 2 != 0:
        if i < atas - 1:
          print(i, end=", ")
        elif i == atas - 1:
          print(i, end=".")
  else:
    for i in range(bawah, atas, -1):
      if i % 2 != 0:
        if i > atas + 1:
          print(i, end=", ")
        elif i == atas + 1:
          print(i, end=".")

bawah = int(input("Masukkan bilangan awal= "))
atas = int(input("Masukkan bilangan akhir= "))

ganjil(bawah,atas)

"""**LATIHAN 5.3**

Buatlah sebuah program penghitung nilai Indeks Prestasi Semester (IPS). Input bagi program:
* Jumlah mata kuliah
* Nilai A, B, C, dan D untuk setiap mata kuliah mahasiswa. Diasumsikan sks setiap mata kuliah selalu 3. Kemudian bobot dari masing-masing nilai adalah: A=4, B=3, C=2, D=1.
Output program ialah hasil IPS yang didapatkan. Jalannya program seperti pada Gambar 5.7.Tips: Gunakan kontrol percabangan di dalam perulangan.
"""

def IPS(matkul, nilai):
  jumlah = 0
  for huruf in nilai:
    if huruf == "A":
      jumlah += 4
    elif huruf == "B":
      jumlah += 3
    elif huruf == "C":
      jumlah += 2
    elif huruf == "D":
      jumlah += 1

  IPS = jumlah / matkul
  print("Nilai IPS anda semester ini =", IPS)

nilai = []
matkul = int(input("Masukkan jumlah mata kuliah = "))
for i in range (matkul):
    i += 1
    huruf = input(f"Nilai MK {i}= ")
    nilai.append(huruf)

IPS(matkul, nilai)
