# -*- coding: utf-8 -*-
"""Rainie Fanita C.H.(71230982) 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15aAQ-CH5FwRNo8Z6vNDeOJsnqAk3cl9A

**LATIHAN 8.1**

Buatlah sebuah program yang dapat membandingkan 2 buah file teks dan kemudian
menampilkan perbedaan antar kedua teks per barisnya jika ada perbedaaan!
"""

def banding(file1, file2):
    with open(file1, "r") as f1:
        ls1 = [line.rstrip() for line in f1]

    with open(file2, "r") as f2:
        ls2 = [line.rstrip() for line in f2]

    gabung = zip(ls1, ls2)
    no = 1
    for l1, l2 in gabung:
        if l1 != l2:
            print(f"Perbedaan di baris {no}:")
            print(f"File 1: {l1}")
            print(f"File 2: {l2}")
        no += 1

file1 = input("Masukkan nama file pertama : ")
file2 = input("Masukkan nama file kedua : ")
banding(file1, file2)

"""**LATIHAN 8.2**

Buatlah sebuah program untuk menampilkan soal sederhana yang diambil dari file teks soal.txt yang memiliki format sebagai berikut:
1+1 = || 2
Bendera Indonesia? || Merah Putih
Kota gudeg adalah: || Yogyakarta
Komponen PC untuk penyimpanan file adalah... || harddisk
50 * 20 = || 1000
Dari soal tersebut tampilkan sbb:
nama file1: soal.txt
1+1 =
Jawab: 2
Jawaban benar!
Bendera Indonesia?
Jawab: merah putih
Jawaban benar!
Kota gudeg adalah:
Jawab: yogya
Jawaban salah!
Komponen PC untuk penyimpanan file adalah...
Jawab: HARDDISK
Jawaban benar!
"""

def kuis(file):
    with open(file, "r") as f:
        ls = [line.rstrip() for line in f]

    for l in ls:
        soal = l.split("||")
        print(f"Pertanyaan: {soal[0]}")
        kunci = soal[1].lower().strip()
        jawaban = input("Jawab: ").lower().strip()

        if kunci == jawaban:
            print("Jawaban benar!")
        else:
            print("Jawaban salah!")

file = input("Sebutkan file soal : ")
kuis(file)