# -*- coding: utf-8 -*-
"""Rainie Fanita C.H.(71230982) 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTl3Z3w5K6_ROB_8KqvzTYXau_lmmzpv

**LATIHAN 5.1**

Buatlah program untuk mencari bilangan prima terdekat dari suatu bilangan yang
diinputkan oleh pengguna (n) dan nilai bilangan prima tersebut < n.
*   Contoh: input n=12, maka prima terdekat < 12 adalah 11
*   Contoh: input n=21, maka prima terdekat < 21 adalah 19
"""

def prima(n):
  if n > 1:
    for i in range (2,n-1):
      if n % i == 0:
        return False
        break
    else:
        return True
  else:
    return False

def terdekat(n):
  turun = n
  naik = n

  if prima(n) == True:
    print(f"input n = {n}, maka prima terdekat < {n} adalah {n}")
  else:
    for i in range (n-1):
      turun -= 1
      naik += 1

      turun_prima = prima(turun)
      naik_prima = prima(naik)

      if turun_prima and naik_prima:
        print(f"input n = {n}, maka prima terdekat < {n} adalah {turun} dan {naik}")
        break
      elif turun_prima and not naik_prima:
        print(f"input n = {n}, maka prima terdekat < {n} adalah {turun}")
        break
      elif naik_prima and not turun_prima:
        print(f"input n = {n}, maka prima terdekat < {n} adalah  {naik}")
        break

n= int(input("Masukkan nilai n = "))
terdekat(n)

"""**LATIHAN 5.2**

Buatlah program untuk menampilkan deret seperti di bawah ini. n diinputkan
secara dinamis
> contoh: n = 6 <br>
> 720 6 5 4 3 2 1 <br>
> 120 5 4 3 2 1<br>
> 24 4 3 2 1<br>
> 6 3 2 1<br>
> 2 2 1<br>
> 1 1
"""

def fibo_kali(n):
  i = n
  while i > 0:
    hasil = 1
    for j in range (i, 0, -1):
      hasil *= j
    print(hasil, end=" ")
    for k in range (i, 0, -1):
      print(k, end=" ")
    i -= 1
    print()

n = int(input("n = "))
fibo_kali(n)

"""**LATIHAN 5.3**

Buatlah program untuk menampilkan deret seperti di bawah ini. n diinputkan
secara dinamis
> contoh: tinggi = 5, lebar = 4<br>
> 1 2 3 4<br>
> 5 6 7 8<br>
> 9 10 11 12<br>
> 13 14 15 16<br>
> 17 18 19 20
"""

def deret(tinggi, lebar):
  i = 1
  while i <= tinggi * lebar:
    for j in range (1, tinggi+1):
      for k in range (1, lebar+1):
        print(i, end=" ")
        i += 1
      print()

tinggi = int(input("Masukkan tinggi = "))
lebar = int(input("Masukkan lebar = "))

deret(tinggi, lebar)